# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: edenlew_development

test:
  <<: *default
  database: edenlew_test

production:
  <<: *default
  database: edenlew_production
